### ISSUE TITLE
Fails with a blank "data:," window in Edge

### ISSUE THREAD

**Issue by seankru** [swartanian/OptumHsaSaveItExport#14]
This looks like maybe an issue with the automation and not this tool:

D:\Users\seank>D:\Users\seank\Desktop\OptumHsaSaveItExportV1.4\OptumHsaSaveItExport.exe manualLogin
Starting Microsoft Edge WebDriver 108.0.1462.46 (d29728ee681767b8b70995c207c659e2b46c2e92) on port 55108
To submit feedback, report a bug, or suggest new features, please visit https://github.com/MicrosoftEdge/EdgeWebDriver

Only local connections are allowed.
Please see https://aka.ms/WebDriverSecurity for suggestions on keeping Microsoft Edge WebDriver safe.

Microsoft Edge WebDriver was started successfully.
Opening in existing browser session.

Unhandled Exception: OpenQA.Selenium.WebDriverException: unknown error: Microsoft Edge failed to start: exited normally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from msedge location C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe is no longer running, so msedgedriver is assuming that msedge has crashed.)
   at OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse, String commandToExecute)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.WebDriver..ctor(ICommandExecutor executor, ICapabilities capabilities)
   at OpenQA.Selenium.Chromium.ChromiumDriver..ctor(ChromiumDriverService service, ChromiumOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Edge.EdgeDriver..ctor(EdgeDriverService service, EdgeOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Edge.EdgeDriver..ctor(EdgeDriverService service, EdgeOptions options)
   at OpenQA.Selenium.Edge.EdgeDriver..ctor(EdgeOptions options)
   at OpenQA.Selenium.Edge.EdgeDriver..ctor()
   at OptumHsaSaveItExport.Program.Main(String[] args) in D:\VsoGit\OptumHsaSaveItExport\Program.cs:line 11

**Comment by swartanian** [comment]
Looks like an Edge setting? 🤷‍♀️
