### ISSUE TITLE
Stuck on HR Benefits page after initial login

### ISSUE THREAD

**Issue by daverupton** [swartanian/OptumHsaSaveItExport#6]
Basic and Full login get stuck on the HR Main page, never getting to the HSA site.  Trace below:

 .\OptumHsaSaveItExport.exe fulllogin
Starting Microsoft Edge WebDriver 107.0.1418.56 (5b47a5c50066f665a52aa4155d30228091b46135) on port 49883
To submit feedback, report a bug, or suggest new features, please visit https://github.com/MicrosoftEdge/EdgeWebDriver

Only local connections are allowed.
Please see https://aka.ms/WebDriverSecurity for suggestions on keeping Microsoft Edge WebDriver safe.

Microsoft Edge WebDriver was started successfully.

DevTools listening on ws://127.0.0.1:49886/devtools/browser/ba39c5e1-9ad0-4d8f-99f9-bbba8424c91f
[93012:91880:1128/104431.179:ERROR:sitelist_downloader.cc(131)] No primary account. Unable to fetch access token.
=====================================================================================
ACTION NEEDED: You have 60 seconds to login.
[93012:91880:1128/104440.033:ERROR:device_event_log_impl.cc(215)] [10:44:40.033] USB: usb_device_handle_win.cc:1048 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[93012:91880:1128/104440.034:ERROR:device_event_log_impl.cc(215)] [10:44:40.034] USB: usb_device_handle_win.cc:1048 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[93012:91880:1128/104440.035:ERROR:device_event_log_impl.cc(215)] [10:44:40.036] USB: usb_device_handle_win.cc:1048 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[93012:91880:1128/104440.036:ERROR:device_event_log_impl.cc(215)] [10:44:40.036] USB: usb_device_handle_win.cc:1048 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)

Unhandled Exception: OpenQA.Selenium.WebDriverTimeoutException: Timed out after 60 seconds ---> OpenQA.Selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"css selector","selector":"#idSIButton9"}
  (Session info: MicrosoftEdge=107.0.1418.52)
   at OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse, String commandToExecute)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.FindElement(String mechanism, String value)
   at OpenQA.Selenium.By.<.ctor>b__11_0(ISearchContext context)
   at OpenQA.Selenium.By.FindElement(ISearchContext context)
   at OpenQA.Selenium.WebDriver.FindElement(By by)
   at SeleniumExtras.WaitHelpers.ExpectedConditions.<>c__DisplayClass19_0.<ElementToBeClickable>b__0(IWebDriver driver)
   at OpenQA.Selenium.Support.UI.DefaultWait`1.Until[TResult](Func`2 condition, CancellationToken token)
   --- End of inner exception stack trace ---
   at OpenQA.Selenium.Support.UI.DefaultWait`1.ThrowTimeoutException(String exceptionMessage, Exception lastException)
   at OpenQA.Selenium.Support.UI.DefaultWait`1.Until[TResult](Func`2 condition, CancellationToken token)
   at OpenQA.Selenium.Support.UI.DefaultWait`1.Until[TResult](Func`2 condition)
   at OptumHsaSaveItExport.UiModel.Login() in C:\dev\source\OptumHsaSaveItExport\UiModel.cs:line 278
   at OptumHsaSaveItExport.Program.Main(String[] args) in C:\dev\source\OptumHsaSaveItExport\Program.cs:line 15
PS C:\dev\source\OptumHsaSaveItExport\bin\Debug>

**Comment by daverupton** [comment]
fixed with login fix
